# Generated by Django 5.2.14 on 2026-05-20 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('symptoms', models.TextField(verbose_name='Síntomas')),
                ('diagnosis', models.TextField(verbose_name='Diagnóstico')),
                ('treatment', models.TextField(verbose_name='Tratamiento')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='doctors.doctor', verbose_name='Médico Responsable')),
            ],
            options={
                'verbose_name': 'Historia Clínica',
                'verbose_name_plural': 'Historias Clínicas',
                'ordering': ['-date'],
            },
        ),
    ]
