# Generated by Django 5.2.14 on 2026-05-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalrecord',
            options={'ordering': ['-created_at'], 'verbose_name': 'Historia Clínica', 'verbose_name_plural': 'Historias Clínicas'},
        ),
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='observations',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='symptoms',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='medications',
            field=models.TextField(blank=True, null=True, verbose_name='Medicamentos Prescritos'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas Adicionales'),
        ),
    ]
